/*
 * This header file was generated by scripts/88colres.pl
 */

package colors

var Color88Lookup []*[3]uint8

func init() {
	Color88Lookup = make([]*[3]uint8, 88)

	/* default system(xterm) colors. WILL vary from others */
	Color88Lookup[0] = &[3]uint8{0, 0, 0}			// black
	Color88Lookup[1] = &[3]uint8{205, 0, 0}			// red3
	Color88Lookup[2] = &[3]uint8{0, 205, 0}			// green3
	Color88Lookup[3] = &[3]uint8{205, 205, 0}		// yellow3
	Color88Lookup[4] = &[3]uint8{0, 0, 238}			// blue2
	Color88Lookup[5] = &[3]uint8{205, 0, 205}		// magenta3
	Color88Lookup[6] = &[3]uint8{0, 205, 205}		// cyan3
	Color88Lookup[7] = &[3]uint8{229, 229, 229}		// gray90
	Color88Lookup[8] = &[3]uint8{127, 127, 127}		// gray50
	Color88Lookup[9] = &[3]uint8{255, 0, 0}			// red
	Color88Lookup[10] = &[3]uint8{0, 255, 0}			// green
	Color88Lookup[11] = &[3]uint8{255, 255, 0}		// yellow
	Color88Lookup[12] = &[3]uint8{92, 92, 255}		// 5c/5c/ff
	Color88Lookup[13] = &[3]uint8{255, 255, 255}		// magenta
	Color88Lookup[14] = &[3]uint8{0, 255, 255}		// cyan
	Color88Lookup[15] = &[3]uint8{255, 255, 255}		// white
	/* default system(xterm) colors end.*/

	Color88Lookup[16] = &[3]uint8{0, 0, 0}
	Color88Lookup[17] = &[3]uint8{0, 0, 139}
	Color88Lookup[18] = &[3]uint8{0, 0, 205}
	Color88Lookup[19] = &[3]uint8{0, 0, 255}
	Color88Lookup[20] = &[3]uint8{0, 139, 0}
	Color88Lookup[21] = &[3]uint8{0, 139, 139}
	Color88Lookup[22] = &[3]uint8{0, 139, 205}
	Color88Lookup[23] = &[3]uint8{0, 139, 255}
	Color88Lookup[24] = &[3]uint8{0, 205, 0}
	Color88Lookup[25] = &[3]uint8{0, 205, 139}
	Color88Lookup[26] = &[3]uint8{0, 205, 205}
	Color88Lookup[27] = &[3]uint8{0, 205, 255}
	Color88Lookup[28] = &[3]uint8{0, 255, 0}
	Color88Lookup[29] = &[3]uint8{0, 255, 139}
	Color88Lookup[30] = &[3]uint8{0, 255, 205}
	Color88Lookup[31] = &[3]uint8{0, 255, 255}
	Color88Lookup[32] = &[3]uint8{139, 0, 0}
	Color88Lookup[33] = &[3]uint8{139, 0, 139}
	Color88Lookup[34] = &[3]uint8{139, 0, 205}
	Color88Lookup[35] = &[3]uint8{139, 0, 255}
	Color88Lookup[36] = &[3]uint8{139, 139, 0}
	Color88Lookup[37] = &[3]uint8{139, 139, 139}
	Color88Lookup[38] = &[3]uint8{139, 139, 205}
	Color88Lookup[39] = &[3]uint8{139, 139, 255}
	Color88Lookup[40] = &[3]uint8{139, 205, 0}
	Color88Lookup[41] = &[3]uint8{139, 205, 139}
	Color88Lookup[42] = &[3]uint8{139, 205, 205}
	Color88Lookup[43] = &[3]uint8{139, 205, 255}
	Color88Lookup[44] = &[3]uint8{139, 255, 0}
	Color88Lookup[45] = &[3]uint8{139, 255, 139}
	Color88Lookup[46] = &[3]uint8{139, 255, 205}
	Color88Lookup[47] = &[3]uint8{139, 255, 255}
	Color88Lookup[48] = &[3]uint8{205, 0, 0}
	Color88Lookup[49] = &[3]uint8{205, 0, 139}
	Color88Lookup[50] = &[3]uint8{205, 0, 205}
	Color88Lookup[51] = &[3]uint8{205, 0, 255}
	Color88Lookup[52] = &[3]uint8{205, 139, 0}
	Color88Lookup[53] = &[3]uint8{205, 139, 139}
	Color88Lookup[54] = &[3]uint8{205, 139, 205}
	Color88Lookup[55] = &[3]uint8{205, 139, 255}
	Color88Lookup[56] = &[3]uint8{205, 205, 0}
	Color88Lookup[57] = &[3]uint8{205, 205, 139}
	Color88Lookup[58] = &[3]uint8{205, 205, 205}
	Color88Lookup[59] = &[3]uint8{205, 205, 255}
	Color88Lookup[60] = &[3]uint8{205, 255, 0}
	Color88Lookup[61] = &[3]uint8{205, 255, 139}
	Color88Lookup[62] = &[3]uint8{205, 255, 205}
	Color88Lookup[63] = &[3]uint8{205, 255, 255}
	Color88Lookup[64] = &[3]uint8{255, 0, 0}
	Color88Lookup[65] = &[3]uint8{255, 0, 139}
	Color88Lookup[66] = &[3]uint8{255, 0, 205}
	Color88Lookup[67] = &[3]uint8{255, 0, 255}
	Color88Lookup[68] = &[3]uint8{255, 139, 0}
	Color88Lookup[69] = &[3]uint8{255, 139, 139}
	Color88Lookup[70] = &[3]uint8{255, 139, 205}
	Color88Lookup[71] = &[3]uint8{255, 139, 255}
	Color88Lookup[72] = &[3]uint8{255, 205, 0}
	Color88Lookup[73] = &[3]uint8{255, 205, 139}
	Color88Lookup[74] = &[3]uint8{255, 205, 205}
	Color88Lookup[75] = &[3]uint8{255, 205, 255}
	Color88Lookup[76] = &[3]uint8{255, 255, 0}
	Color88Lookup[77] = &[3]uint8{255, 255, 139}
	Color88Lookup[78] = &[3]uint8{255, 255, 205}
	Color88Lookup[79] = &[3]uint8{255, 255, 255}
	Color88Lookup[80] = &[3]uint8{46, 46, 46}
	Color88Lookup[81] = &[3]uint8{92, 92, 92}
	Color88Lookup[82] = &[3]uint8{115, 115, 115}
	Color88Lookup[83] = &[3]uint8{139, 139, 139}
	Color88Lookup[84] = &[3]uint8{162, 162, 162}
	Color88Lookup[85] = &[3]uint8{185, 185, 185}
	Color88Lookup[86] = &[3]uint8{208, 208, 208}
	Color88Lookup[87] = &[3]uint8{231, 231, 231}
}
