#! /usr/bin/env bash

echo "/*"
echo " * This header file was generated by $0"
echo " */"
echo ""

cat <<EOF
package colors

var ColorCSSLookup map[string]*[3]uint8

func init() {
	ColorCSSLookup = make(map[string]*[3]uint8)

EOF

cat scripts/css3-color/colors.txt | while read -r line;
do
  color=$( echo ${line} | cut -d'|' -f1 )
  rgb=$( echo ${line} | cut -d'|' -f2 )

  echo -e '\tColorCSSLookup["'${color}'"] = &[3]uint8{'${rgb}'}'
done

cat <<EOF

}
EOF
